apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
spec:
  initContainers:
  - name: builder
    image: docker:20.10.9
    command: ["/bin/sh"]
    args: ["-c", "apk add --no-cache git && git clone https://github.com/alexanderogorodnikov/tech-a build -t hello-world-image ./docker"]
  containers:
  - name: hello-world
    image: hello-world-image
    # Add other hello-world container configurations here

