apiVersion: v1
kind: Pod
metadata:
  name: {{ include "hello-world-chart.fullname" . }}
spec:
  initContainers:
  - name: builder
    image: quay.io/podman/stable
    volumeMounts:
    - name: shared-volume
      mountPath: /share
      mountPropagation: Bidirectional
    - name: host
      mountPath: /host
    command: ["/bin/sh"]
    args: ["-c", "yum install git -y && git clone https://github.com/alexanderogorodnikov/tech-a && cd ./tech-a/docker && podman build -t localhost/hello-world:latest -f ./Dockerfile && podman save --format oci-archive -o /share/hello-world.tar localhost/hello-world:latest && nsenter --mount=/host/proc/1/ns/mnt ctr -n=k8s.io image import /tmp/hello-world.tar"]
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
          - ALL
      privileged: true
  containers:
  - name: hello-world
    image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
  volumes:
  - name: shared-volume
    hostPath:
      path: /tmp
      type: Directory
  - name: host
    hostPath:
      path: /
      type: ''
